In [ ]:
import numpy as np
print(np.__version__)

2.3.5


In [3]:
array = np.array(10)
print(array)

10


In [4]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


In [6]:
arr3 = np.array(arr2)
print(arr3)

[1 2 3 4 5]


In [7]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4)

[[1 2 3]
 [4 5 6]]


In [14]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5)
print(arr5.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
